/*******************************************************************************
**
**   Project: GEOStar-1
**
**       $Id: acgpstable.c 4616 2014-03-06 16:06:07Z millerw $
**  $HeadURL: http://vasvn01/svn/Tenacious/trunk/aquila/dev/fsw/fc/adcs/acgpstable.c $
** $Revision: 4616 $
**     $Date: 2014-03-06 11:06:07 -0500 (Thu, 06 Mar 2014) $
**    Author: This file was auto-generated by Composer for Optus D3.
**
** Copyright (c) Orbital Sciences Corporation, 2011.
**               Unpublished — Rights Reserved under the Copyright Laws of the
**               United States.  This computer software is a trade secret of
**               Orbital Sciences Corporation and shall not be reproduced,
**               disclosed, or used without prior written permission of Orbital
**               Sciences Corporation.
**
*******************************************************************************/

/*
** GPS Parameter Table ...
*/

#include "acstypes.h"
#include "acsdefines.h"
#include "acgpstable.h"

ac_gps_table_type AcGpsTable = {
  0xFFFE,                                  /* CycleMask, GPS Command Cycle Mask (10 Hz)      */
  0xFFFE,                                  /* FrameMask, GPS Frame Mask, Every Frame 1 - 15  */
  0,                                       /* Spare                                          */
  3 * NUM_AN_CYCLES,                       /* PowerOffCnt , AN Cycles                        */
  {                                        /* Fdc */
    10 * NUM_AC_CYCLES,                    /* PowerStatusOffCnt , AC Cycles */
    4 * HR_2_SEC*NUM_AN_CYCLES,            /* RangeLoadTestCnt  , AN Cycles */
    1 * HR_2_SEC*NUM_AN_CYCLES,            /* PosChanLoadTestCnt, AN Cycles */
    0 * NUM_AN_CYCLES,                     /* GoodsModeTestCnt  , AN Cycles */
    60 * NUM_AN_CYCLES,                    /* WarmupTimer       , AN Cycles */
    30 * NUM_AN_CYCLES,                    /* RangeUpdateTimer  , AN Cycles */
    {0,0},
  }
};
