/*******************************************************************************
**
**   Project: GEOStar-1
**
**       $Id: acgpstable.h 4189 2012-12-04 19:59:03Z millerw $
**  $HeadURL: http://vasvn01/svn/Tenacious/trunk/aquila/dev/fsw/fc/adcs/acgpstable.h $
** $Revision: 4189 $
**     $Date: 2012-12-04 14:59:03 -0500 (Tue, 04 Dec 2012) $
**    Author: This file to be auto-generated by Composer.
**
** Copyright (c) Orbital Sciences Corporation, 2012.
**               Unpublished — Rights Reserved under the Copyright Laws of the
**               United States.  This computer software is a trade secret of
**               Orbital Sciences Corporation and shall not be reproduced,
**               disclosed, or used without prior written permission of Orbital
**               Sciences Corporation.
**
*******************************************************************************/

/************************************/
#pragma pack()       /* Green Hills */
/************************************/


#ifndef _acgpstable_h_
#define _acgpstable_h_

#pragma pack(4)

/* GPS Parameter Table */
typedef struct
{
  uWord CycleMask;
  uWord FrameMask;
  uWord Spare;
  uWord PowerOffCnt;

  struct {
    uWord  PowerStatusOffCnt;       /* GPS Power Status Off Count, cnt */
    uWord  RangeLoadTestCnt;
    uWord  PosChanLoadTestCnt;
    uWord  GoodsModeTestCnt;
    uWord  WarmupTimer;
    uWord  RangeUpdateTimer;
    uWord  Spare[2];
  } Fdc;
} ac_gps_table_type;

#endif

/************************************/
#pragma pack()       /* Green Hills */
/************************************/
