 /*********************************************************************************************************************
 *
 *  File:                acirutable.h
 *
 *  Last modification:   2012-12-04
 *
 *  Author:              auto-generated by Composer
 *
 *  COPYRIGHT (C):       2020. Northrop Grumman Corporation.  Unless otherwise marked, all files 
 *                       contained herein are Northrop Grumman Proprietary Level <I> 
 *
 *  COPYRIGHT NOTICE:    All information contained herein is, and remains the property of the
 *                       Northrop Grumman Corporation. The intellectual and technical concepts
 *                       contained herein are proprietary to Northrop Grumman Systems Corporation 
 *                       and may be covered by U.S. and Foreign Patents, patents in process, and  
 *                       are protected by trade secret or copyright law. Dissemination of this 
 *                       information or reproduction of this material is strictly forbidden unless 
 *                       prior written permission is obtained from Northrop Grumman. 
 *
 *  WARNING:             The export of technical data without approval from the U.S. Department
 *                       of State is prohibited under the U.S. Arms Export Control Act, Title 22,
 *                       U.S.C., Sec. 2751, et. seq. and the International Traffic in Arms
 *                       Regulations (ITAR), 22 C.F.R. Sec. 120 et seq.   Violations of these laws
 *                       and regulations carry severe criminal penalties.
 *
 *  DESTRUCTION NOTICE:  Destroy by any method that will prevent disclosure of contents or
 *                       reconstruction.
 *                       
 *********************************************************************************************************************/


/************************************/
#pragma pack()       /* Green Hills */
/************************************/


#ifndef _acirutable_h_
#define _acirutable_h_

#pragma pack(4)

typedef struct
{
    uWord  PowerStatusOffCnt                          ; /* IRU Power Status Off Count, cnt */
    uWord  ConstantTimeCnt                            ; /* IRU Constant Time Count, cnt */
    uWord  ResonatorTempCnt                           ; /* IRU Resonator Temperature Test Count, */
    uWord  GyroStatusErrCnt       [NUM_OF_GYR]        ; /* Gyro Status Error Count, cnt */
    uWord  AccelStatusErrCnt      [NUM_OF_ACC]        ; /* Accel Status Error Count, cnt */
    uWord  ConstantAngleDataCnt   [NUM_OF_GYR]        ; /* Gyro Constant Angle Data Count, cnt */
    uWord  ConstantVelDataCnt     [NUM_OF_ACC]        ; /* Accel Constant Velocity Data Count, cnt */
    uWord  AngleGlitchCnt         [NUM_OF_GYR]        ; /* Angle Glitch Test Count, cnt */
    uWord  AccelGlitchCnt         [NUM_OF_ACC]        ; /* Accel Glitch Test Count, cnt */
    uWord  IruCorrectCnt                              ; /* IRU Correction Count, cnt */
    uWord  IruVerifyCnt                               ; /* IRU Verification Count, cnt */
    uWord  IruSafeSwitchWaitCnt                       ; /* IRU Safe Switch RTS Wait Count, cnt */
    uWord  IruSafeSwitchVerifyCnt                     ; /* IRU Safe Switch RTS Verification Count, cnt */
    uWord  SpareWord                                  ; /* Padding */
    dReal  AngleGlitchThr         [NUM_OF_GYR]        ; /* Angle Glitch Test Threshold, rad */
    dReal  AccelGlitchThr         [NUM_OF_ACC]        ; /* Accel Glitch Test Threshold, m/s */
    dReal  ResonatorTempHiThr                         ; /* Gyro Resonator Temperature High Threshold, deg C */
    dReal  ResonatorTempLoThr                         ; /* Gyro Resonator Temperature Low Threshold, deg C */
} ac_iru_table_fdc_type;

/* Inertial Reference Unit Parameter Table */
typedef struct
{
    uMatrix  DcmBdytoIru                                      ; /* Body to IRU Transformation Matrix*/
    uVector  DcmIruToGyr         [NUM_OF_GYR]                 ; /* IRU to Gyro Transformation Matrix, ND */
    uVector  DcmIruToAcc         [NUM_OF_ACC]                 ; /* IRU to Accel Transformation Matrix */
    uVector  IruPositionScFrame                               ; /* Location of SSIRU coord. frame in the SC frame */
    uVector  AccPositionIru      [NUM_OF_ACC]                 ; /* Location of each accel ECM in the SSIRU frame relative to the frame origin*/
    dReal    ThetaLatency[NUM_IRU_CYCLES_PER_AC_CYCLE]        ; /* ThetaLatency (sec) */
    dReal    OmegaLatency[NUM_IRU_CYCLES_PER_AC_CYCLE]        ; /* OmegaLatency (sec) */
    dReal    GyrAngleWhiteNoise                               ; /* Gyro Angle White Noise For KF Q, rad^2 */
    dReal    GyrAngleRandomWalk                               ; /* Gyro Angle Random Walk For KF Q, rad^2/sec */
    dReal    GyrRateRandomWalk                                ; /* Gyro Rate Random Walk For KF Q, rad^2/sec^3 */
    dReal    ScaleFactor      [2][NUM_OF_GYR]                 ; /* 2x4 Matrix Of Gyro Scale Factors, rad/LSB */
    dReal    AccelScaleFactor    [NUM_OF_ACC]                 ; /* 1x4 Vector Of Accel Scale Factors, (mm/s)/LSB */
    dReal    DefaultGyrBias      [NUM_OF_GYR]                 ; /* Default Gyro Bias, rad/sec */
    dReal    DefaultAccBias      [NUM_OF_ACC]                 ; /* Default Accel Bias, m/sec^2 */
    uVector  IruBiasLmt                                       ; /* IRU Bias Limit, rad/sec */
    dReal    TimeScaleFactor                                  ; /* Time Scale Factor, sec/cnt */
    dReal    WarmUpTime                                       ; /* Warm Up Time, sec */
    dword    TimeCntMax                                       ; /* Maximum Time Count, cnt */
    uWord    EnableGyroLatencyCompDefault                     ; /* Default state for enabling/disabling Gyro Latency Compensation [TRUE/FALSE]         */
    uWord    EnaGyroLatencyCompDuringBusSlew                  ; /* Whether gyro latency compensation is enabled/disabled during SV slews [TRUE/FALSE]  */
    uWord    EnaGyroLatencyCompInPldState[NUM_PAYLOAD_STATES] ; /* Which payload modes enable latency compensation [TRUE/FALSE]                        */
    uWord    QuiescentPayloadState[NUM_PAYLOAD_STATES]        ; /* Flag that prevents autopilot effort during payload slews */
    uWord    PowerOffCnt                                      ; /* IRU power off counter initial value, ACS Cycles */
    uWord    Spare[3]                                         ; /* padding */
    ac_iru_table_fdc_type Fdc;
} ac_iru_table_type;

#endif

/************************************/
#pragma pack()       /* Green Hills */
/************************************/
