 /*********************************************************************************************************************
 *
 *  File:                acirutable.c
 *
 *  Last modification:   2014-03-06
 *
 *  Author:              auto-generated by Composer
 *
 *  COPYRIGHT (C):       2020. Northrop Grumman Corporation.  Unless otherwise marked, all files
 *                       contained herein are Northrop Grumman Proprietary Level <I>
 *
 *  COPYRIGHT NOTICE:    All information contained herein is, and remains the property of the
 *                       Northrop Grumman Corporation. The intellectual and technical concepts
 *                       contained herein are proprietary to Northrop Grumman Systems Corporation
 *                       and may be covered by U.S. and Foreign Patents, patents in process, and
 *                       are protected by trade secret or copyright law. Dissemination of this
 *                       information or reproduction of this material is strictly forbidden unless
 *                       prior written permission is obtained from Northrop Grumman.
 *
 *  WARNING:             The export of technical data without approval from the U.S. Department
 *                       of State is prohibited under the U.S. Arms Export Control Act, Title 22,
 *                       U.S.C., Sec. 2751, et. seq. and the International Traffic in Arms
 *                       Regulations (ITAR), 22 C.F.R. Sec. 120 et seq.   Violations of these laws
 *                       and regulations carry severe criminal penalties.
 *
 *  DESTRUCTION NOTICE:  Destroy by any method that will prevent disclosure of contents or
 *                       reconstruction.
 *
 *********************************************************************************************************************/


/*
** Inertial Reference Unit Parameter Table ...
*/

#include "acstypes.h"
#include "acsdefines.h"
#include "acirutable.h"

ac_iru_table_type AcIruTable = {
  {{{   0.0,   0.0,   1.0},    /*DcmBdyToIru*/
    {  -1.0,   0.0,   0.0},
    {   0.0,  -1.0,   0.0}}},

  /* The Following Values Are Design Values (Perfect Alignment) based on DN-SERAPHIM-GNC-001 rev A Sect. 4.2.1.2 */
  {{{   0.577350269189626,   0.577350269189626,   0.577350269189626  }},   /* DcmIruToGyr[GYRA], ND */
   {{   0.577350269189626,  -0.577350269189626,   0.577350269189626  }},   /* DcmIruToGyr[GYRB], ND */
   {{  -0.577350269189626,  -0.577350269189626,   0.577350269189626  }},   /* DcmIruToGyr[GYRC], ND */
   {{  -0.577350269189626,   0.577350269189626,   0.577350269189626  }}},  /* DcmIruToGyr[GYRD], ND */

  /* Accelerometer DCMs: Design Values (Perfect Alignment) based on DN-SERAPHIM-GNC-326 Sect. 4.5.3 */
  {{{  -0.577350269189626,   0.577350269189626,   0.577350269189626  }},   /* DcmIruToAcc[ACCA], ND */
   {{  -0.577350269189626,  -0.577350269189626,   0.577350269189626  }},   /* DcmIruToAcc[ACCB], ND */
   {{   0.577350269189626,  -0.577350269189626,   0.577350269189626  }},   /* DcmIruToAcc[ACCC], ND */
   {{   0.577350269189626,   0.577350269189626,   0.577350269189626  }}},  /* DcmIruToAcc[ACCD], ND */

   /* SSIRU Frame location in the SC frame */
   /* Reference: SER-GNC-MEMO-005 SSIRU Location Table 2 */
   {   0.3938,   0.4864,   1.0333 },              /* IruPositionScFrame, m */

  /* Accelerometer ECM positions in the SSIRU coordinate frame relative to the origin */
  /* Accelerometer positions based on Seraphim SSIRU Accelerometer Locations Rev A*/
  /* Reference: SER-GNC-MEMO-005 SSIRU Location Table 1*/
  {{{   0.02122,  0.09204,  0.02908 }},       /* AccPositionIru[ACCA][3], m */
   {{   0.02122, -0.09204,  0.02908 }},       /* AccPositionIru[ACCB][3], m */
   {{  -0.02122, -0.09204,  0.02908 }},       /* AccPositionIru[ACCC][3], m */
   {{  -0.02122,  0.09204,  0.02908 }}},      /* AccPositionIru[ACCC][3], m */

  { 35.0e-3 + MF_CYCLE_TIME,                             /* ThetaLatency (sec) */
    35.0e-3 + MF_CYCLE_TIME } ,
  { 35.0e-3 + MF_CYCLE_TIME + 0.5 * IRU_CYCLE_TIME,      /* OmegaLatency (sec) */
    35.0e-3 + MF_CYCLE_TIME + 0.5 * IRU_CYCLE_TIME }   ,

  SQR(0.00794   * ARCSEC_2_RAD)   , /* [rad^2           ] GyrAngleWhiteNoise [0.003 arc-sec/rt(Hz)*rt(7Hz)(B.W.)] */
  SQR(0.009     * ARCSEC_2_RAD)   , /* [rad^2/sec       ] GyrAngleRandomWalk */
  SQR(0         * ARCSEC_2_RAD)   , /* [rad^2/sec^3     ] GyrRateRandomWalk */
{
  0.05*ARCSEC_2_RAD               , /* [rad/LSB, GYRA   ] ScaleFactor[0][0] */
  0.05*ARCSEC_2_RAD               , /* [rad/LSB, GYRB   ] ScaleFactor[0][1] */
  0.05*ARCSEC_2_RAD               , /* [rad/LSB, GYRC   ] ScaleFactor[0][2] */
  0.05*ARCSEC_2_RAD               , /* [rad/LSB, GYRD   ] ScaleFactor[0][3] */
  1.60*ARCSEC_2_RAD               , /* [rad/LSB, GYRA   ] ScaleFactor[1][0] */
  1.60*ARCSEC_2_RAD               , /* [rad/LSB, GYRB   ] ScaleFactor[1][1] */
  1.60*ARCSEC_2_RAD               , /* [rad/LSB, GYRC   ] ScaleFactor[1][2] */
  1.60*ARCSEC_2_RAD                 /* [rad/LSB, GYRD   ] ScaleFactor[1][3] */
},
{
  1.2207E-9                       , /* [(m/s)/LSB, ACCA ] AccelScaleFactor[0], SSIRU EICD - 6B04982 Rev A Section 4.6.2.8*/
  1.2207E-9                       , /* [(m/s)/LSB, ACCB ] AccelScaleFactor[1], SSIRU EICD - 6B04982 Rev A Section 4.6.2.8*/
  1.2207E-9                       , /* [(m/s)/LSB, ACCB ] AccelScaleFactor[2], SSIRU EICD - 6B04982 Rev A Section 4.6.2.8*/
  1.2207E-9                       , /* [(m/s)/LSB, ACCB ] AccelScaleFactor[3], SSIRU EICD - 6B04982 Rev A Section 4.6.2.8*/
},
{
  0.0                             , /* [rad/sec, GYRA   ] DefaultGyrBias[0] */
  0.0                             , /* [rad/sec, GYRB   ] DefaultGyrBias[1] */
  0.0                             , /* [rad/sec, GYRC   ] DefaultGyrBias[2] */
  0.0                               /* [rad/sec, GYRD   ] DefaultGyrBias[3] */
},
{
  0.018                           , /* [m/sec^2, ACCA   ] DefaultAccBias[0] */
  0.018                           , /* [m/sec^2, ACCB   ] DefaultAccBias[1] */
  0.018                           , /* [m/sec^2, ACCC   ] DefaultAccBias[2] */
  0.018                             /* [m/sec^2, ACCD   ] DefaultAccBias[3] */
},
{
{
  4.0*ARCSEC_2_RAD                , /* [rad/sec         ] IruBiasLmt.v[0] */
  4.0*ARCSEC_2_RAD                , /* [rad/sec         ] IruBiasLmt.v[1] */
  4.0*ARCSEC_2_RAD                  /* [rad/sec         ] IruBiasLmt.v[2] */
}
},
  4.0E-6                          , /* [sec/cnt         ] TimeScaleFactor */
  400.0                           , /* [sec             ] WarmUpTime */
  65535                           , /* [cnt             ] TimeCntMax */
  TRUE                            , /* [True/False      ] EnableGyroLatencyCompDefault */
  TRUE                            , /* [True/False      ] EnaGyroLatencyCompDuringBusSlew */

  {                                 /* EnaGyroLatencyCompInPldState */
    FALSE                         , /* [True/False      ] PD_FAULT       */
    FALSE                         , /* [True/False      ] PD_IDLE        */
    FALSE                         , /* [True/False      ] PD_HOLD        */
    TRUE                          , /* [True/False      ] PD_SLEWING     */
    FALSE                         , /* [True/False      ] PD_TRACKING    */
    TRUE                          , /* [True/False      ] PD_DECELERATE  */
    FALSE                         , /* [True/False      ] PD_TRACK_TABLE */
    TRUE                            /* [True/False      ] PD_COMM_ANGLE  */
  },

  {                                 /* QuiescentPayloadState */
    TRUE                          , /* [True/False      ] PD_FAULT       */
    TRUE                          , /* [True/False      ] PD_IDLE        */
    TRUE                          , /* [True/False      ] PD_HOLD        */
    FALSE                         , /* [True/False      ] PD_SLEWING     */
    TRUE                          , /* [True/False      ] PD_TRACKING    */
    FALSE                         , /* [True/False      ] PD_DECELERATE  */
    TRUE                          , /* [True/False      ] PD_TRACK_TABLE */
    FALSE                           /* [True/False      ] PD_COMM_ANGLE  */
  },
  3*NUM_AC_CYCLES                 , /* [cnt             ] PowerOffCnt    */
  {
    0                             , /*                    Spare[0]       */
    0                             , /*                    Spare[1]       */
    0                               /*                    Spare[2]       */
  },
{
  15*NUM_AC_CYCLES                , /* [cnt             ] Fdc.PowerStatusOffCnt */
  15*NUM_IRU_CYCLES               , /* [cnt             ] Fdc.ConstantTimeCnt */
  60*NUM_IRU_CYCLES               , /* [cnt             ] Fdc.ResonatorTempCnt */
{
  15*NUM_IRU_CYCLES               , /* [cnt, GYRA       ] Fdc.GyroStatusErrCnt[0] */
  15*NUM_IRU_CYCLES               , /* [cnt, GYRB       ] Fdc.GyroStatusErrCnt[1] */
  15*NUM_IRU_CYCLES               , /* [cnt, GYRC       ] Fdc.GyroStatusErrCnt[2] */
  15*NUM_IRU_CYCLES                 /* [cnt, GYRD       ] Fdc.GyroStatusErrCnt[3] */
},
{
  15*NUM_AC_CYCLES                , /* [cnt, ACCA       ] Fdc.AccelStatusErrCnt[0] */
  15*NUM_AC_CYCLES                , /* [cnt, ACCB       ] Fdc.AccelStatusErrCnt[1] */
  15*NUM_AC_CYCLES                , /* [cnt, ACCC       ] Fdc.AccelStatusErrCnt[2] */
  15*NUM_AC_CYCLES                  /* [cnt, ACCD       ] Fdc.AccelStatusErrCnt[3] */
},
{
  30*NUM_IRU_CYCLES               , /* [cnt, GYRA       ] Fdc.ConstantAngleDataCnt[0] */
  30*NUM_IRU_CYCLES               , /* [cnt, GYRB       ] Fdc.ConstantAngleDataCnt[1] */
  30*NUM_IRU_CYCLES               , /* [cnt, GYRC       ] Fdc.ConstantAngleDataCnt[2] */
  30*NUM_IRU_CYCLES                 /* [cnt, GYRD       ] Fdc.ConstantAngleDataCnt[3] */
},
{
  30*NUM_AC_CYCLES                , /* [cnt, ACCA       ] Fdc.ConstantVelDataCnt[0] */
  30*NUM_AC_CYCLES                , /* [cnt, ACCB       ] Fdc.ConstantVelDataCnt[1] */
  30*NUM_AC_CYCLES                , /* [cnt, ACCC       ] Fdc.ConstantVelDataCnt[2] */
  30*NUM_AC_CYCLES                  /* [cnt, ACCD       ] Fdc.ConstantVelDataCnt[3] */
},
{
  4                               , /* [cnt, GYRA       ] Fdc.AngleGlitchCnt[0] */
  4                               , /* [cnt, GYRB       ] Fdc.AngleGlitchCnt[1] */
  4                               , /* [cnt, GYRC       ] Fdc.AngleGlitchCnt[2] */
  4                                 /* [cnt, GYRD       ] Fdc.AngleGlitchCnt[3] */
},
{
  4                               , /* [cnt, ACCA       ] Fdc.AccelGlitchCnt[0] */
  4                               , /* [cnt, ACCB       ] Fdc.AccelGlitchCnt[1] */
  4                               , /* [cnt, ACCC       ] Fdc.AccelGlitchCnt[2] */
  4                                 /* [cnt, ACCD       ] Fdc.AccelGlitchCnt[3] */
},
  460*NUM_AC_CYCLES               , /* [cnt                             ] Fdc.IruCorrectCnt */
  120*NUM_AC_CYCLES               , /* [cnt                             ] Fdc.IruVerifyCnt */
  600 * NUM_AC_CYCLES             , /* [cnt                             ] Fdc.IruSafeSwitchWaitCnt */
  900 * NUM_AC_CYCLES             , /* [cnt, >IruCorrectCnt+IruVerifyCnt] Fdc.IruSafeSwitchVerifyCnt */
  0                               , /* [                                ] Fdc.SpareWord */
{
  0.11 * DEG_2_RAD                , /* [rad, GYRA       ] Fdc.AngleGlitchThr[0] [1.0 deg/sec slew req't] */
  0.11 * DEG_2_RAD                , /* [rad, GYRB       ] Fdc.AngleGlitchThr[1] */
  0.11 * DEG_2_RAD                , /* [rad, GYRC       ] Fdc.AngleGlitchThr[2] */
  0.11 * DEG_2_RAD                  /* [rad, GYRD       ] Fdc.AngleGlitchThr[3] */
},
{
  0.017                           , /* [m/s, ACCA       ] Fdc.AccelGlitchThr[0] [2 x BRE Capability at EOL] */
  0.017                           , /* [m/s, ACCB       ] Fdc.AccelGlitchThr[1] */
  0.017                           , /* [m/s, ACCC       ] Fdc.AccelGlitchThr[2] */
  0.017                             /* [m/s, ACCD       ] Fdc.AccelGlitchThr[3] */
},
  80.0                            , /* [deg C           ] Fdc.ResonatorTempHiThr */
  60.0                              /* [deg C           ] Fdc.ResonatorTempLoThr */
},
};
