 /*********************************************************************************************************************
 *
 *  File:                aclunartable.c
 *
 *  Last modification:   2011-12-13
 *
 *  Author:              auto-generated by Composer
 *
 *  COPYRIGHT (C):       2020. Northrop Grumman Corporation.  Unless otherwise marked, all files
 *                       contained herein are Northrop Grumman Proprietary Level <I>
 *
 *  COPYRIGHT NOTICE:    All information contained herein is, and remains the property of the
 *                       Northrop Grumman Corporation. The intellectual and technical concepts
 *                       contained herein are proprietary to Northrop Grumman Systems Corporation
 *                       and may be covered by U.S. and Foreign Patents, patents in process, and
 *                       are protected by trade secret or copyright law. Dissemination of this
 *                       information or reproduction of this material is strictly forbidden unless
 *                       prior written permission is obtained from Northrop Grumman.
 *
 *  WARNING:             The export of technical data without approval from the U.S. Department
 *                       of State is prohibited under the U.S. Arms Export Control Act, Title 22,
 *                       U.S.C., Sec. 2751, et. seq. and the International Traffic in Arms
 *                       Regulations (ITAR), 22 C.F.R. Sec. 120 et seq.   Violations of these laws
 *                       and regulations carry severe criminal penalties.
 *
 *  DESTRUCTION NOTICE:  Destroy by any method that will prevent disclosure of contents or
 *                       reconstruction.
 *
 *********************************************************************************************************************/


#include "acstypes.h"
#include "acsdefines.h"
#include "aclunartable.h"

/*
** Lunar Ephemeris Parameter Table ...
*/

ac_lunar_table_type  AcLunarTable =
{
  218.32     * DEG_2_RAD                , /* [rad             ] LML1 */
  481267.883 * DEG_2_RAD / CENTURY_2_DAY, /* [rad             ] LML2 */
  6.29       * DEG_2_RAD                , /* [rad             ] LML3 */
  1.27       * DEG_2_RAD                , /* [rad             ] LML4 */
  0.66       * DEG_2_RAD                , /* [rad             ] LML5 */
  0.21       * DEG_2_RAD                , /* [rad             ] LML6 */
  0.19       * DEG_2_RAD                , /* [rad             ] LML7 */
  0.11       * DEG_2_RAD                , /* [rad             ] LML8 */
  134.9      * DEG_2_RAD                , /* [rad             ] LMLP1 */
  259.2      * DEG_2_RAD                , /* [rad             ] LMLP2 */
  235.7      * DEG_2_RAD                , /* [rad             ] LMLP3 */
  269.9      * DEG_2_RAD                , /* [rad             ] LMLP4 */
  357.5      * DEG_2_RAD                , /* [rad             ] LMLP5 */
  186.6      * DEG_2_RAD                , /* [rad             ] LMLP6 */
  477198.85  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMLW1 */
  413335.38  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMLW2 */
  890534.23  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMLW3 */
  954397.70  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMLW4 */
  35999.05   * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMLW5 */
  966404.05  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMLW6 */
  5.13       * DEG_2_RAD                , /* [rad             ] LMB1 */
  0.28       * DEG_2_RAD                , /* [rad             ] LMB2 */
  0.28       * DEG_2_RAD                , /* [rad             ] LMB3 */
  0.17       * DEG_2_RAD                , /* [rad             ] LMB4 */
  93.3       * DEG_2_RAD                , /* [rad             ] LMBP1 */
  228.2      * DEG_2_RAD                , /* [rad             ] LMBP2 */
  318.3      * DEG_2_RAD                , /* [rad             ] LMBP3 */
  217.6      * DEG_2_RAD                , /* [rad             ] LMBP4 */
  483202.03  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMBW1 */
  960400.87  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMBW2 */
  6003.18    * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMBW3 */
  407332.20  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMBW4 */
  0.9175                                , /* [ND              ] LMC1 */
  0.3978                                , /* [ND              ] LMC2 */
  0.3978                                , /* [ND              ] LMC3 */
  0.9175                                , /* [ND              ] LMC4 */
  0.9508     * DEG_2_RAD                , /* [rad             ] LMP1 */
  0.0518     * DEG_2_RAD                , /* [rad             ] LMP2 */
  0.0095     * DEG_2_RAD                , /* [rad             ] LMP3 */
  0.0078     * DEG_2_RAD                , /* [rad             ] LMP4 */
  0.0028     * DEG_2_RAD                , /* [rad             ] LMP5 */
  134.9      * DEG_2_RAD                , /* [rad             ] LMPP1 */
  259.2      * DEG_2_RAD                , /* [rad             ] LMPP2 */
  235.7      * DEG_2_RAD                , /* [rad             ] LMPP3 */
  269.9      * DEG_2_RAD                , /* [rad             ] LMPP4 */
  477198.85  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMPW1 */
  413335.38  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMPW2 */
  890534.23  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMPW3 */
  954397.70  * DEG_2_RAD / CENTURY_2_DAY, /* [rad/jd          ] LMPW4 */
  6378136.6                               /* [m               ] RE0 */
};

