 /*********************************************************************************************************************
 *
 *  File:                aclunartable.h
 *
 *  Last modification:   2012-10-12
 *
 *  Author:              auto-generated by Composer
 *
 *  COPYRIGHT (C):       2020. Northrop Grumman Corporation.  Unless otherwise marked, all files 
 *                       contained herein are Northrop Grumman Proprietary Level <I> 
 *
 *  COPYRIGHT NOTICE:    All information contained herein is, and remains the property of the
 *                       Northrop Grumman Corporation. The intellectual and technical concepts
 *                       contained herein are proprietary to Northrop Grumman Systems Corporation 
 *                       and may be covered by U.S. and Foreign Patents, patents in process, and  
 *                       are protected by trade secret or copyright law. Dissemination of this 
 *                       information or reproduction of this material is strictly forbidden unless 
 *                       prior written permission is obtained from Northrop Grumman. 
 *
 *  WARNING:             The export of technical data without approval from the U.S. Department
 *                       of State is prohibited under the U.S. Arms Export Control Act, Title 22,
 *                       U.S.C., Sec. 2751, et. seq. and the International Traffic in Arms
 *                       Regulations (ITAR), 22 C.F.R. Sec. 120 et seq.   Violations of these laws
 *                       and regulations carry severe criminal penalties.
 *
 *  DESTRUCTION NOTICE:  Destroy by any method that will prevent disclosure of contents or
 *                       reconstruction.
 *                       
 *********************************************************************************************************************/
 

#ifndef _aclunartable_h_
#define _aclunartable_h_

#pragma pack(4)

/*
** Lunar Ephemeris Parameter Table (Coefficients From 1997 Astronomical Almanac) ...
*/

typedef struct ac_lunar_table_ {
  dReal LML1;       /* Ecliptic Longitude Equation Coefficient (rad) */
  dReal LML2;       /* Ecliptic Longitude Equation Coefficient (rad) */
  dReal LML3;       /* Ecliptic Longitude Equation Coefficient (rad) */
  dReal LML4;       /* Ecliptic Longitude Equation Coefficient (rad) */
  dReal LML5;       /* Ecliptic Longitude Equation Coefficient (rad) */
  dReal LML6;       /* Ecliptic Longitude Equation Coefficient (rad) */
  dReal LML7;       /* Ecliptic Longitude Equation Coefficient (rad) */
  dReal LML8;       /* Ecliptic Longitude Equation Coefficient (rad) */
  dReal LMLP1;      /* Ecliptic Longitude Equation Phase Constant (rad) */
  dReal LMLP2;      /* Ecliptic Longitude Equation Phase Constant (rad) */
  dReal LMLP3;      /* Ecliptic Longitude Equation Phase Constant (rad) */
  dReal LMLP4;      /* Ecliptic Longitude Equation Phase Constant (rad) */
  dReal LMLP5;      /* Ecliptic Longitude Equation Phase Constant (rad) */
  dReal LMLP6;      /* Ecliptic Longitude Equation Phase Constant (rad) */
  dReal LMLW1;      /* Ecliptic Longitude Equation Frequency Constant (rad/jd) */
  dReal LMLW2;      /* Ecliptic Longitude Equation Frequency Constant (rad/jd) */
  dReal LMLW3;      /* Ecliptic Longitude Equation Frequency Constant (rad/jd) */
  dReal LMLW4;      /* Ecliptic Longitude Equation Frequency Constant (rad/jd) */
  dReal LMLW5;      /* Ecliptic Longitude Equation Frequency Constant (rad/jd) */
  dReal LMLW6;      /* Ecliptic Longitude Equation Frequency Constant (rad/jd) */
  dReal LMB1;       /* Ecliptic Latitude Equation Coefficient (rad) */
  dReal LMB2;       /* Ecliptic Latitude Equation Coefficient (rad) */
  dReal LMB3;       /* Ecliptic Latitude Equation Coefficient (rad) */
  dReal LMB4;       /* Ecliptic Latitude Equation Coefficient (rad) */
  dReal LMBP1;      /* Ecliptic Latitude Equation Phase Constant (rad) */
  dReal LMBP2;      /* Ecliptic Latitude Equation Phase Constant (rad) */
  dReal LMBP3;      /* Ecliptic Latitude Equation Phase Constant (rad) */
  dReal LMBP4;      /* Ecliptic Latitude Equation Phase Constant (rad) */
  dReal LMBW1;      /* Ecliptic Latitude Equation Frequency Constant (rad/jd) */
  dReal LMBW2;      /* Ecliptic Latitude Equation Frequency Constant (rad/jd) */
  dReal LMBW3;      /* Ecliptic Latitude Equation Frequency Constant (rad/jd) */
  dReal LMBW4;      /* Ecliptic Latitude Equation Frequency Constant (rad/jd) */
  dReal LMC1;       /* Cosine Of Inclination Of Ecliptic Plane (nd) */
  dReal LMC2;       /* Sine Of Inclination Of Ecliptic Plane (nd) */
  dReal LMC3;       /* Sine Of Inclination Of Ecliptic Plane (nd) */
  dReal LMC4;       /* Cosine Of Inclination Of Ecliptic Plane (nd) */
  dReal LMP1;       /* Parallex Equation Coefficient (rad) */
  dReal LMP2;       /* Parallex Equation Coefficient (rad) */
  dReal LMP3;       /* Parallex Equation Coefficient (rad) */
  dReal LMP4;       /* Parallex Equation Coefficient (rad) */
  dReal LMP5;       /* Parallex Equation Coefficient (rad) */
  dReal LMPP1;      /* Parallex Equation Phase Constant (rad) */
  dReal LMPP2;      /* Parallex Equation Phase Constant (rad) */
  dReal LMPP3;      /* Parallex Equation Phase Constant (rad) */
  dReal LMPP4;      /* Parallex Equation Phase Constant (rad) */
  dReal LMPW1;      /* Parallex Equation Frequency Constant (rad/jd) */
  dReal LMPW2;      /* Parallex Equation Frequency Constant (rad/jd) */
  dReal LMPW3;      /* Parallex Equation Frequency Constant (rad/jd) */
  dReal LMPW4;      /* Parallex Equation Frequency Constant (rad/jd) */
  dReal RE0;        /* Earth Radius (m) */
} ac_lunar_table_type;

/************************************/
#pragma pack()       /* Green Hills */
/************************************/

#endif
